name: Continuous Integration

on: [push]

jobs:
  build-test-vscode:
    name: Build and test the VSCode extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g typescript
    - run: npm install -g vsce
    - run: npm install
    - name: Package VSCode extension into .vsix file
      run: vsce package
    - name: Start xvfb only if it's Linux
      run:
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"
      shell: bash
    - name: npm install, build, and test
      run:
        npm test
      env:
        DISPLAY: ':99.0' # Only necessary for linux tests