name: Continuous Integration

on: [push]

jobs:
  build-test-vscode:
    name: Build and test the VSCode extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g typescript
    - run: npm install -g vsce
    - run: npm install
    - name: Package VSCode extension into .vsix file
      run: vsce package
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
        if: runner.os != 'Linux'